### ISSUE TITLE
Tracking issue for 0.1 release

### ISSUE THREAD

**Issue by boguslavsky** [exonum/exonum-doc#25]
@boguslavsky:

- [x] Update theme to [mkdocs-material](http://squidfunk.github.io/mkdocs-material/extensions/metadata/). Task: #28, PR: #33
- [x] SEO meta tags (beautiful posts on Facebook, Twitter, Skype, Slack etc.). PR: #43
- [ ] Cryptocurrency step-by-step manual. Task: #37
